version: '3.7'

services:
    mysql:
      container_name: smport
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=smport
      security_opt:
        - seccomp:unconfined
      ports:
        - 3306:3306
      networks:
        - local
      volumes:
        - ./db:/var/lib/mysql

networks:
  local:
